### ISSUE TITLE
my zones are not placing

### ISSUE THREAD

**Issue by xKingSo** [GMSpeedruns/GM-BunnyHop#2]
on the gm bunnyhop i cant get my zones to place but when i switch back to flow they are on there how would i fix this

**Comment by fibzeih** [comment]
Stop stealing peoples files and learn your self

**Comment by xKingSo** [comment]
how is this stealing isn't this a public release

**Comment by SaengerItsWar** [comment]
The flow Timer https://github.com/GMSpeedruns/Flow-Release is the old version of this Timer and it also was or is public and it's the same developer. That means it's a rewrite of the old one
